---
- name: Clone git repository to roles directory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure roles directory exists
      ansible.builtin.file:
        path: "roles"
        state: directory
        mode: '0755'

    - name: Clone the git repository into the roles directory
      ansible.builtin.git:
        key_file: ~/.ssh/github
        accept_hostkey: true
        repo: "git@github.com:sarych/ansible-roles.git"
        dest: "roles"
        version: main
        force: true
